# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3e09142b0420fc2ed91dfec6a275fcedf97381f9d88d2b75f91e8958fff4d84a0b057beefd3fb4fcbaa89ac86972a6b8d07646a8823e927d2f3d0e6c049151f

test:
  secret_key_base: 0f34befd2fe3a6e807125ca3f4c18a303ccbc8647c1566e96cc972903bd6fa47f4d94bb3e8fda18e67dd315ffb9ae44027ca466ed352fbf5c30bab4e191acd95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
